specVersion: 0.0.2
description: An automated market maker for pegged value crypto assets
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum/contract
    name: ArbUSDPool
    network: arbitrum-one
    source:
      address: "0xBea9F78090bDB9e662d8CB301A00ad09A5b756e9"
      abi: SwapFlashLoanNoWithdrawFee
      startBlock: 3073795
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      language: wasm/assemblyscript
      entities:
        - Swap
        - SystemInfo
        - Token
        - NewAdminFeeEvent
        - NewSwapFeeEvent
        - RampAEvent
        - StopRampAEvent
        - AddLiquidityEvent
        - RemoveLiquidityEvent
        - FlashLoanEvent
        - TokenExchange
      abis:
        - name: SwapFlashLoanNoWithdrawFee
          file: ./abis/SwapFlashLoanNoWithdrawFee.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: NewAdminFee(uint256)
          handler: handleNewAdminFee
        - event: NewSwapFee(uint256)
          handler: handleNewSwapFee
        - event: RampA(uint256,uint256,uint256,uint256)
          handler: handleRampA
        - event: StopRampA(uint256,uint256)
          handler: handleStopRampA
        - event: AddLiquidity(indexed address,uint256[],uint256[],uint256,uint256)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(indexed address,uint256[],uint256)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityImbalance(indexed address,uint256[],uint256[],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
        - event: RemoveLiquidityOne(indexed address,uint256,uint256,uint256,uint256)
          handler: handleRemoveLiquidityOne
        - event: FlashLoan(indexed address,uint8,uint256,uint256,uint256)
          handler: handleFlashLoan
        - event: TokenSwap(indexed address,uint256,uint256,uint128,uint128)
          handler: handleTokenSwap
      file: ./src/mappings/swapFlashLoanNoWithdrawFee.ts

  - kind: ethereum/contract
    name: "frax-ArbUSD Pool V2"
    network: arbitrum-one
    source:
      address: "0xfeEa4D1BacB0519E8f952460A70719944fe56Ee0"
      abi: SwapFlashLoanNoWithdrawFee
      startBlock: 4006435
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.4
      language: wasm/assemblyscript
      entities:
        - Swap
        - SystemInfo
        - Token
        - NewAdminFeeEvent
        - NewSwapFeeEvent
        - RampAEvent
        - StopRampAEvent
        - AddLiquidityEvent
        - RemoveLiquidityEvent
        - FlashLoanEvent
        - TokenExchange
      abis:
        - name: SwapFlashLoanNoWithdrawFee
          file: ./abis/SwapFlashLoanNoWithdrawFee.json
        - name: ERC20
          file: ./abis/ERC20.json
      eventHandlers:
        - event: NewAdminFee(uint256)
          handler: handleNewAdminFee
        - event: NewSwapFee(uint256)
          handler: handleNewSwapFee
        - event: RampA(uint256,uint256,uint256,uint256)
          handler: handleRampA
        - event: StopRampA(uint256,uint256)
          handler: handleStopRampA
        - event: AddLiquidity(indexed address,uint256[],uint256[],uint256,uint256)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(indexed address,uint256[],uint256)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityImbalance(indexed address,uint256[],uint256[],uint256,uint256)
          handler: handleRemoveLiquidityImbalance
        - event: RemoveLiquidityOne(indexed address,uint256,uint256,uint256,uint256)
          handler: handleRemoveLiquidityOne
        - event: FlashLoan(indexed address,uint8,uint256,uint256,uint256)
          handler: handleFlashLoan
        - event: TokenSwap(indexed address,uint256,uint256,uint128,uint128)
          handler: handleTokenSwap
      file: ./src/mappings/swapFlashLoanNoWithdrawFee.ts
